/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RenderFormImport } from './routes/render-form'
import { Route as CreateFormImport } from './routes/create-form'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const RenderFormRoute = RenderFormImport.update({
  id: '/render-form',
  path: '/render-form',
  getParentRoute: () => rootRoute,
} as any)

const CreateFormRoute = CreateFormImport.update({
  id: '/create-form',
  path: '/create-form',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-form': {
      id: '/create-form'
      path: '/create-form'
      fullPath: '/create-form'
      preLoaderRoute: typeof CreateFormImport
      parentRoute: typeof rootRoute
    }
    '/render-form': {
      id: '/render-form'
      path: '/render-form'
      fullPath: '/render-form'
      preLoaderRoute: typeof RenderFormImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-form': typeof CreateFormRoute
  '/render-form': typeof RenderFormRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-form': typeof CreateFormRoute
  '/render-form': typeof RenderFormRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create-form': typeof CreateFormRoute
  '/render-form': typeof RenderFormRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-form' | '/render-form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-form' | '/render-form'
  id: '__root__' | '/' | '/create-form' | '/render-form'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateFormRoute: typeof CreateFormRoute
  RenderFormRoute: typeof RenderFormRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateFormRoute: CreateFormRoute,
  RenderFormRoute: RenderFormRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-form",
        "/render-form"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-form": {
      "filePath": "create-form.tsx"
    },
    "/render-form": {
      "filePath": "render-form.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
